import {environment} from "../../../environments/environment";

export const endpoints = environment.endpoins;
export const api = endpoints.api;
export const login = endpoints.login;
export const register = endpoints.register;
export const teacher = endpoints.teacher;
export const group = endpoints.group;
export const children = endpoints.children;
export const attendance = endpoints.attendance;
export const announcement = endpoints.announcement;
export const payment = endpoints.payment;
export const registrationRequest = endpoints.registrationRequest;
export const extensionRequest = endpoints.extensionRequest;
export const get = endpoints.get;
export const add = endpoints.add;
export const update = endpoints.update;
export const deleteEnd = endpoints.delete;
export const all = endpoints.all;
export const spots = endpoints.spots;
